apiVersion: v1
kind: ServiceAccount
metadata:
  name: postfix
  namespace: mailserver
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mailserver
  name: mailmanager
rules:
  - apiGroups: [""]
    resources: ["configmaps","secrets"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mailmanager
  namespace: mailserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mailmanager
subjects:
- kind: ServiceAccount
  name: postfix
